---
applications:
- application: simtools-generate-array-config
  configuration:
    array_layout_name:
      by_version:
        "<7.0.0": alpha
        ">=7.0.0": CTAO-North-Alpha
    model_version: 6.0.2
    output_path: __TEST_DIRECTORY__/simtools-tests/__SIMTOOLS_VERSION__/integration_tests/tmp_application_output
    site: North
    label: test
collection:
  output_path: __TEST_DIRECTORY__/simtools-tests/__SIMTOOLS_VERSION__/integration_tests/generated/sim_telarray_configurations/6.0.2
  files:
  - model/6.0.2/CTA-alpha-North_test.cfg
  - model/6.0.2/CTA-North-LSTN-01_test.cfg
  - model/6.0.2/CTA-North-LSTN-02_test.cfg
  - model/6.0.2/CTA-North-MSTN-01_test.cfg
schema_name: application_workflow.metaschema
schema_url: https://github.com/gammasim/simtools/blob/main/src/simtools/schemas/application_workflow.metaschema.yml
schema_version: 0.4.0
