---
applications:
- application: simtools-db-get-parameter-from-db
  configuration:
    output_path: __TEST_DIRECTORY__/simtools-tests/__SIMTOOLS_VERSION__/integration_tests/tmp_application_output
    output_file: array_layouts-2.0.2.json
    parameter: array_layouts
    parameter_version: 2.0.2
    site: North
collection:
  output_path: __TEST_DIRECTORY__/simtools-tests/__SIMTOOLS_VERSION__/integration_tests/generated
  files:
  - array_layouts-2.0.2.json
schema_name: application_workflow.metaschema
schema_url: https://github.com/gammasim/simtools/blob/main/src/simtools/schemas/application_workflow.metaschema.yml
schema_version: 0.4.0
